import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, BarChart, Bar
} from 'recharts';
import { stocksAPI, predictionsAPI, sectorsAPI } from '../utils/api';
import {
  formatPrice, formatMarketCap, formatVolume,
  getDirectionEmoji, getConfidenceColor, timeAgo
} from '../utils/format';

const PERIOD_OPTIONS = [
  { label: '1M', value: '1mo' }, { label: '3M', value: '3mo' },
  { label: '6M', value: '6mo' }, { label: '1Y', value: '1y'  },
  { label: '2Y', value: '2y'  }, { label: '5Y', value: '5y'  },
];

const DISCLAIMER = "⚠️ NOT FINANCIAL ADVICE — All predictions are generated by automated algorithms for informational purposes only. Past performance does not guarantee future results. This platform does not provide investment advice. Always consult a licensed financial advisor before making any investment decisions.";

const StockDetail = () => {
  const { ticker } = useParams();
  const navigate   = useNavigate();

  const [stock,      setStock]      = useState(null);
  const [history,    setHistory]    = useState([]);
  const [prediction, setPrediction] = useState(null);
  const [news,       setNews]       = useState([]);
  const [period,     setPeriod]     = useState('1y');
  const [loading,    setLoading]    = useState(true);
  const [chartLoading, setChartLoading] = useState(false);
  const [predLoading,  setPredLoading]  = useState(false);
  const [predLoaded,   setPredLoaded]   = useState(false);   // lazy flag
  const [activeTab,    setActiveTab]    = useState('overview');
  const [sectors,      setSectors]      = useState({});

  // ── Load stock + news + sectors (on mount and ticker change) ───────────────
  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const [stockRes, newsRes, sectorRes] = await Promise.allSettled([
        stocksAPI.getDetail(ticker),
        stocksAPI.getNews(ticker),
        sectorsAPI.getSectors(),
      ]);
      if (stockRes.status  === 'fulfilled') setStock(stockRes.value.data);
      if (newsRes.status   === 'fulfilled') setNews(newsRes.value.data.news || []);
      if (sectorRes.status === 'fulfilled') setSectors(sectorRes.value.data.sectors || {});
    } catch (e) { console.error(e); }
    setLoading(false);
  }, [ticker]);

  // ── Load history separately so period changes don't re-fetch stock ─────────
  const loadHistory = useCallback(async () => {
    setChartLoading(true);
    try {
      const res = await stocksAPI.getHistory(ticker, period);
      setHistory(res.data.data || []);
    } catch (e) { console.error(e); }
    setChartLoading(false);
  }, [ticker, period]);

  // ── Lazy prediction load — only fires when user clicks the Prediction tab ──
  const loadPrediction = useCallback(async (forceRefresh = false) => {
    if (predLoaded && !forceRefresh) return;
    setPredLoading(true);
    try {
      const url = forceRefresh ? ticker + '?refresh=true' : ticker;
      const res  = await predictionsAPI.getPrediction(url);
      setPrediction(res.data);
      setPredLoaded(true);
    } catch (e) { console.error(e); }
    setPredLoading(false);
  }, [ticker, predLoaded]);

  useEffect(() => {
    setHistory([]);
    setPrediction(null);
    setPredLoaded(false);
    loadData();
  }, [ticker]);                          // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => { loadHistory(); }, [loadHistory]);

  // Only load prediction when prediction tab is first activated
  useEffect(() => {
    if (activeTab === 'prediction' && !predLoaded) {
      loadPrediction();
    }
  }, [activeTab]);                       // eslint-disable-line react-hooks/exhaustive-deps

  const chartData = history.map(h => ({
    date:   new Date(h.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
    close:  h.close ? parseFloat(h.close.toFixed(2)) : null,
    volume: h.volume,
  })).filter(d => d.close != null);

  const prices   = chartData.map(d => d.close).filter(Boolean);
  const minPrice = prices.length ? Math.min(...prices) * 0.99 : 0;
  const maxPrice = prices.length ? Math.max(...prices) * 1.01 : 100;

  const s          = stock || {};
  const changePct  = s.change_pct;
  const priceColor = changePct > 0 ? '#00f5a0' : changePct < 0 ? '#ff4757' : '#4a9eff';
  const changeColor= changePct > 0 ? 'var(--accent-green)' : changePct < 0 ? 'var(--accent-red)' : 'var(--text-secondary)';

  const CustomTooltip = ({ active, payload, label }) => {
    if (!active || !payload?.length) return null;
    return (
      <div style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border)', borderRadius: 4, padding: '8px 12px', fontFamily: 'var(--font-mono)' }}>
        <div style={{ color: 'var(--text-muted)', fontSize: 10, marginBottom: 4 }}>{label}</div>
        <div style={{ color: priceColor, fontSize: 14, fontWeight: 700 }}>{formatPrice(payload[0]?.value)}</div>
      </div>
    );
  };

  if (loading && !stock) {
    return (
      <div style={{ padding: 40, textAlign: 'center', fontFamily: 'var(--font-mono)', color: 'var(--text-muted)' }}>
        <div style={{ color: 'var(--accent-green)', marginBottom: 12, fontSize: 18 }}>
          Loading {ticker}<span className="cursor" />
        </div>
        <div style={{ fontSize: 11 }}>Fetching market data...</div>
      </div>
    );
  }

  return (
    <div style={styles.page}>
      <div style={styles.nav}>
        <button style={styles.backBtn} onClick={() => navigate('/')}>← BACK TO TERMINAL</button>
        <div style={styles.breadcrumb}>
          <span style={{ color: 'var(--text-muted)' }}>GPST</span>
          <span style={{ color: 'var(--text-muted)', margin: '0 6px' }}>/</span>
          <span style={{ color: 'var(--accent-cyan)' }}>{ticker}</span>
        </div>
      </div>

      {/* Hero */}
      <div style={styles.hero}>
        <div style={styles.heroLeft}>
          <div style={styles.tickerBig}>{ticker}</div>
          <div style={styles.companyNameBig}>{s.name || ticker}</div>
          <div style={styles.metaTags}>
            {s.exchange && <span style={styles.tag}>{s.exchange}</span>}
            {s.sector   && <span style={{ ...styles.tag, borderColor: 'rgba(139,92,246,0.4)', color: 'var(--accent-purple)' }}>{s.sector}</span>}
            {s.country  && <span style={styles.tag}>{s.country}</span>}
          </div>
        </div>
        <div style={styles.heroRight}>
          <div style={styles.priceBig}>{formatPrice(s.current_price, s.currency)}</div>
          {changePct != null && (
            <div style={{ ...styles.changeBig, color: changeColor }}>
              {changePct > 0 ? '▲' : changePct < 0 ? '▼' : '●'} {Math.abs(changePct).toFixed(2)}%
            </div>
          )}
          <div style={styles.heroStats}>
            {[
              ['MKT CAP', formatMarketCap(s.market_cap)],
              ['VOLUME',  formatVolume(s.volume)],
              ['P/E',     s.pe_ratio?.toFixed(1) || '—'],
              ['52W HI',  formatPrice(s.fifty_two_week_high)],
              ['52W LO',  formatPrice(s.fifty_two_week_low)],
              ['BETA',    s.beta?.toFixed(2) || '—'],
            ].map(([label, val]) => (
              <div key={label} style={styles.heroStat}>
                <span style={styles.heroStatLabel}>{label}</span>
                <span style={styles.heroStatVal}>{val}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div style={styles.tabs}>
        {['overview', 'prediction', 'news', 'profile'].map(tab => (
          <button
            key={tab}
            style={{ ...styles.tab, ...(activeTab === tab ? styles.tabActive : {}) }}
            onClick={() => setActiveTab(tab)}
          >{tab.toUpperCase()}</button>
        ))}
      </div>

      <div style={styles.content}>

        {/* OVERVIEW */}
        {activeTab === 'overview' && (
          <div className="fade-in">
            <div style={styles.periodSelector}>
              <span style={{ color: 'var(--text-muted)', fontSize: 10, marginRight: 12 }}>PERIOD:</span>
              {PERIOD_OPTIONS.map(opt => (
                <button
                  key={opt.value}
                  style={{ ...styles.periodBtn, ...(period === opt.value ? styles.periodBtnActive : {}) }}
                  onClick={() => setPeriod(opt.value)}
                >{opt.label}</button>
              ))}
            </div>

            <div style={styles.chartCard}>
              <div style={styles.chartTitle}>
                <span style={{ color: 'var(--accent-cyan)' }}>PRICE HISTORY</span>
                <span style={{ color: 'var(--text-muted)', fontSize: 10 }}>{period.toUpperCase()} · {chartData.length} DATA POINTS</span>
              </div>
              {chartLoading ? (
                <div style={{ height: 300, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <span style={{ color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', fontSize: 12 }}>
                    Loading chart<span className="cursor" />
                  </span>
                </div>
              ) : chartData.length > 0 ? (
                <ResponsiveContainer width="100%" height={300}>
                  <AreaChart data={chartData} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                    <defs>
                      <linearGradient id="priceGrad" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%"  stopColor={priceColor} stopOpacity={0.15} />
                        <stop offset="95%" stopColor={priceColor} stopOpacity={0} />
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="2 4" stroke="rgba(255,255,255,0.04)" />
                    <XAxis dataKey="date" tick={{ fill: 'var(--text-muted)', fontSize: 10 }} tickLine={false} axisLine={{ stroke: 'var(--border)' }} interval={Math.floor(chartData.length / 8)} />
                    <YAxis domain={[minPrice, maxPrice]} tick={{ fill: 'var(--text-muted)', fontSize: 10 }} tickLine={false} axisLine={false} tickFormatter={v => `$${v.toFixed(0)}`} width={60} />
                    <Tooltip content={<CustomTooltip />} />
                    <Area type="monotone" dataKey="close" stroke={priceColor} strokeWidth={1.5} fill="url(#priceGrad)" dot={false} activeDot={{ r: 4, fill: priceColor }} />
                  </AreaChart>
                </ResponsiveContainer>
              ) : (
                <div style={styles.noData}>NO CHART DATA AVAILABLE</div>
              )}
            </div>

            {!chartLoading && chartData.length > 0 && (
              <div style={{ ...styles.chartCard, marginTop: 12 }}>
                <div style={styles.chartTitle}><span style={{ color: 'var(--text-secondary)' }}>VOLUME (Millions)</span></div>
                <ResponsiveContainer width="100%" height={100}>
                  <BarChart data={chartData.slice(-60)} margin={{ top: 0, right: 10, left: 0, bottom: 0 }}>
                    <XAxis dataKey="date" hide />
                    <YAxis hide />
                    <Tooltip formatter={(v) => [`${(v/1e6).toFixed(1)}M`, 'Volume']} contentStyle={{ background: 'var(--bg-elevated)', border: '1px solid var(--border)', borderRadius: 4, fontSize: 11 }} />
                    <Bar dataKey="volume" fill="rgba(74,158,255,0.3)" stroke="rgba(74,158,255,0.5)" strokeWidth={0} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            )}

            {Object.keys(sectors).length > 0 && (
              <div style={{ ...styles.chartCard, marginTop: 16 }}>
                <div style={styles.chartTitle}><span style={{ color: 'var(--accent-cyan)' }}>SECTOR PERFORMANCE TODAY</span></div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {Object.entries(sectors).map(([name, data]) => {
                    const chg      = data.change_pct || 0;
                    const barColor = chg > 0 ? 'var(--accent-green)' : 'var(--accent-red)';
                    const isActive = name === s.sector;
                    return (
                      <div key={name} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '6px 8px', borderRadius: 'var(--radius)', ...(isActive ? { background: 'rgba(0,210,255,0.05)', border: '1px solid rgba(0,210,255,0.1)' } : {}) }}>
                        <span style={{ color: isActive ? 'var(--accent-cyan)' : 'var(--text-secondary)', fontSize: 11, minWidth: 160 }}>
                          {isActive ? '▶ ' : ''}{name}
                        </span>
                        <div style={{ flex: 1, height: 4, background: 'var(--bg-elevated)', borderRadius: 2, overflow: 'hidden' }}>
                          <div style={{ width: `${Math.min(100, Math.abs(chg) * 20)}%`, height: '100%', background: barColor, borderRadius: 2 }} />
                        </div>
                        <span style={{ color: barColor, fontSize: 11, minWidth: 60, textAlign: 'right' }}>
                          {chg > 0 ? '+' : ''}{chg.toFixed(2)}%
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </div>
        )}

        {/* PREDICTION */}
        {activeTab === 'prediction' && (
          <div className="fade-in">
            <div style={styles.disclaimerBox}>{DISCLAIMER}</div>

            {predLoading ? (
              <div style={{ ...styles.chartCard, textAlign: 'center', padding: 40, fontFamily: 'var(--font-mono)' }}>
                <div style={{ color: 'var(--accent-green)', marginBottom: 8 }}>Running predictive engine<span className="cursor" /></div>
                <div style={{ color: 'var(--text-muted)', fontSize: 11 }}>Analyzing technical indicators, news sentiment, macro data...</div>
              </div>
            ) : prediction ? (
              <div>
                <div style={{ ...styles.chartCard, borderColor: 'var(--border-active)', marginBottom: 16 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20, fontFamily: 'var(--font-mono)' }}>
                    <div>
                      <div style={{ color: 'var(--text-muted)', fontSize: 10, marginBottom: 4 }}>AI PREDICTION · NEXT TRADING DAY</div>
                      <div style={{ color: 'var(--text-secondary)', fontSize: 11 }}>
                        Generated: {prediction.prediction_date ? new Date(prediction.prediction_date).toLocaleString() : '—'}
                      </div>
                    </div>
                    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 4 }}>
                      <div style={{ fontSize: 9, color: 'var(--text-muted)' }}>
                        Model: {prediction.model_version}
                        {prediction.cached && <span style={{ color: 'var(--accent-amber)', marginLeft: 8 }}>CACHED</span>}
                      </div>
                      {/* Force refresh button */}
                      <button
                        style={{ fontSize: 9, background: 'transparent', border: '1px solid var(--border)', color: 'var(--text-muted)', padding: '2px 8px', borderRadius: 'var(--radius)', cursor: 'pointer', fontFamily: 'var(--font-mono)' }}
                        onClick={() => loadPrediction(true)}
                      >↻ REFRESH</button>
                    </div>
                  </div>

                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr 1fr', gap: 24, alignItems: 'start' }}>
                    <div style={{ textAlign: 'center' }}>
                      <div style={{
                        fontFamily: 'var(--font-display)', fontSize: 32, fontWeight: 800, marginBottom: 8,
                        color: prediction.predicted_direction === 'UP'   ? 'var(--accent-green)' :
                               prediction.predicted_direction === 'DOWN' ? 'var(--accent-red)'   : 'var(--accent-amber)'
                      }}>
                        {getDirectionEmoji(prediction.predicted_direction)} {prediction.predicted_direction}
                      </div>
                      <div style={{ fontSize: 14, color: 'var(--text-secondary)', fontFamily: 'var(--font-mono)' }}>
                        Est. {prediction.predicted_change_pct > 0 ? '+' : ''}{prediction.predicted_change_pct?.toFixed(2)}%
                      </div>
                      {prediction.ml_available && (
                        <div style={{ marginTop: 8, fontSize: 9, color: 'var(--accent-purple)', border: '1px solid rgba(139,92,246,0.3)', borderRadius: 2, padding: '2px 6px', display: 'inline-block' }}>
                          ML · {prediction.ml_val_accuracy ? `${(prediction.ml_val_accuracy * 100).toFixed(1)}% val acc` : 'active'}
                        </div>
                      )}
                    </div>

                    <div>
                      <div style={{ fontSize: 9, color: 'var(--text-muted)', letterSpacing: '0.15em', marginBottom: 8 }}>PROBABILITY DISTRIBUTION</div>
                      <div style={{ height: 32, display: 'flex', borderRadius: 4, overflow: 'hidden', border: '1px solid var(--border)' }}>
                        <div style={{ width: `${(prediction.probability_up || 0) * 100}%`, background: 'rgba(0,245,160,0.3)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 10, color: 'var(--accent-green)', fontFamily: 'var(--font-mono)', minWidth: 50 }}>
                          {((prediction.probability_up || 0) * 100).toFixed(0)}% UP
                        </div>
                        <div style={{ width: `${(prediction.probability_neutral || 0) * 100}%`, background: 'rgba(74,158,255,0.2)' }} />
                        <div style={{ width: `${(prediction.probability_down || 0) * 100}%`, background: 'rgba(255,71,87,0.3)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 10, color: 'var(--accent-red)', fontFamily: 'var(--font-mono)', minWidth: 50 }}>
                          {((prediction.probability_down || 0) * 100).toFixed(0)}% DOWN
                        </div>
                      </div>
                      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 9, marginTop: 4, fontFamily: 'var(--font-mono)' }}>
                        <span style={{ color: 'var(--accent-green)' }}>BULLISH</span>
                        <span style={{ color: 'var(--text-muted)'  }}>NEUTRAL</span>
                        <span style={{ color: 'var(--accent-red)'  }}>BEARISH</span>
                      </div>
                    </div>

                    <div style={{ textAlign: 'center' }}>
                      <div style={{ fontSize: 9, color: 'var(--text-muted)', letterSpacing: '0.15em', marginBottom: 8 }}>CONFIDENCE LEVEL</div>
                      <div style={{ height: 6, background: 'var(--bg-elevated)', borderRadius: 3, overflow: 'hidden', marginTop: 8 }}>
                        <div style={{ width: `${(prediction.confidence || 0) * 100}%`, height: '100%', borderRadius: 3, background: getConfidenceColor(prediction.confidence), transition: 'width 1s ease' }} />
                      </div>
                      <div style={{ color: getConfidenceColor(prediction.confidence), fontSize: 20, fontWeight: 700, marginTop: 8 }}>
                        {((prediction.confidence || 0) * 100).toFixed(1)}%
                      </div>
                    </div>
                  </div>
                </div>

                {prediction.features_used && (
                  <div style={{ ...styles.chartCard, marginBottom: 16 }}>
                    <div style={styles.chartTitle}><span>SIGNAL BREAKDOWN</span></div>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                      {Object.entries({
                        'Technical Analysis': prediction.features_used.technical_score,
                        'News Sentiment':     prediction.features_used.sentiment_score,
                        'Macro Conditions':   prediction.features_used.macro_score,
                        'Sector Momentum':    prediction.features_used.sector_score,
                        ...(prediction.features_used.ml_ensemble_prob != null
                          ? { 'ML Ensemble': (prediction.features_used.ml_ensemble_prob - 0.5) * 2 }
                          : {}),
                      }).map(([name, score]) => {
                        const pct   = ((score + 1) / 2 * 100);
                        const color = pct > 60 ? 'var(--accent-green)' : pct < 40 ? 'var(--accent-red)' : 'var(--accent-amber)';
                        return (
                          <div key={name}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                              <span style={{ color: 'var(--text-secondary)', fontSize: 10 }}>{name}</span>
                              <span style={{ color, fontSize: 10 }}>{pct.toFixed(0)}/100</span>
                            </div>
                            <div style={{ height: 4, background: 'var(--bg-elevated)', borderRadius: 2, overflow: 'hidden' }}>
                              <div style={{ width: `${pct}%`, height: '100%', background: color, borderRadius: 2 }} />
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

                <div style={{ ...styles.chartCard, marginBottom: 16 }}>
                  <div style={styles.chartTitle}><span>PREDICTION RATIONALE & ANALYSIS</span></div>
                  <pre style={{ fontSize: 11, color: 'var(--text-secondary)', lineHeight: 1.8, whiteSpace: 'pre-wrap', fontFamily: 'var(--font-mono)', overflow: 'auto' }}>
                    {prediction.rationale}
                  </pre>
                </div>

                {prediction.sources_used?.length > 0 && (
                  <div style={styles.chartCard}>
                    <div style={styles.chartTitle}><span>DATA SOURCES USED</span></div>
                    {prediction.sources_used.map((src, i) => (
                      <div key={i} style={{ fontSize: 11, color: 'var(--text-secondary)', fontFamily: 'var(--font-mono)', padding: '4px 0', borderBottom: '1px solid rgba(30,42,66,0.5)' }}>
                        <span style={{ color: 'var(--accent-green)', marginRight: 8 }}>◆</span>{src}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ) : (
              <div style={styles.noData}>PREDICTION UNAVAILABLE — Try again shortly</div>
            )}
          </div>
        )}

        {/* NEWS */}
        {activeTab === 'news' && (
          <div className="fade-in">
            {news.length === 0 ? (
              <div style={styles.noData}>NO NEWS DATA AVAILABLE</div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                {news.map((item, i) => (
                  <div key={i} style={{ ...styles.chartCard }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
                      <span style={{ fontSize: 10, color: 'var(--accent-amber)', letterSpacing: '0.1em', fontFamily: 'var(--font-mono)' }}>{item.source}</span>
                      <span style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>{timeAgo(item.published_at)}</span>
                    </div>
                    <a href={item.url} target="_blank" rel="noreferrer" style={{ fontSize: 14, color: 'var(--text-primary)', lineHeight: 1.4, display: 'block', marginBottom: 8, fontFamily: 'var(--font-display)', fontWeight: 600 }}>
                      {item.title}
                    </a>
                    {item.summary && <div style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{item.summary}</div>}
                    {item.sentiment != null && item.sentiment !== 0 && (
                      <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginTop: 8 }}>
                        SENTIMENT:
                        <span style={{ color: item.sentiment > 0 ? 'var(--accent-green)' : 'var(--accent-red)', marginLeft: 6 }}>
                          {item.sentiment > 0 ? '▲ POSITIVE' : '▼ NEGATIVE'} ({item.sentiment > 0 ? '+' : ''}{(item.sentiment * 100).toFixed(0)}%)
                        </span>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* PROFILE */}
        {activeTab === 'profile' && (
          <div className="fade-in">
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
              <div style={styles.chartCard}>
                <div style={styles.chartTitle}><span>COMPANY PROFILE</span></div>
                {s.description
                  ? <p style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 20 }}>{s.description}</p>
                  : <div style={styles.noData}>No description available</div>}
                <div style={{ display: 'flex', flexDirection: 'column', gap: 10, borderTop: '1px solid var(--border)', paddingTop: 16 }}>
                  {[
                    ['Website',   s.website ? <a href={s.website} target="_blank" rel="noreferrer" style={{ color: 'var(--accent-cyan)' }}>{s.website}</a> : '—'],
                    ['Country',   s.country   || '—'],
                    ['Employees', s.employees?.toLocaleString() || '—'],
                    ['Sector',    s.sector    || '—'],
                    ['Industry',  s.industry  || '—'],
                    ['Exchange',  s.exchange  || '—'],
                  ].map(([label, val]) => (
                    <div key={label} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                      <span style={{ fontSize: 10, color: 'var(--text-muted)', letterSpacing: '0.1em', fontFamily: 'var(--font-mono)' }}>{label}</span>
                      <span style={{ fontSize: 12, color: 'var(--text-primary)', textAlign: 'right', maxWidth: '60%' }}>{val}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div style={styles.chartCard}>
                <div style={styles.chartTitle}><span>KEY STATISTICS</span></div>
                {[
                  ['Market Cap',      formatMarketCap(s.market_cap)],
                  ['P/E Ratio (TTM)', s.pe_ratio?.toFixed(2)       || '—'],
                  ['Forward P/E',     s.forward_pe?.toFixed(2)     || '—'],
                  ['Dividend Yield',  s.dividend_yield ? `${(s.dividend_yield * 100).toFixed(2)}%` : '—'],
                  ['52W High',        formatPrice(s.fifty_two_week_high)],
                  ['52W Low',         formatPrice(s.fifty_two_week_low)],
                  ['Beta',            s.beta?.toFixed(2)           || '—'],
                  ['Avg Volume',      formatVolume(s.avg_volume)],
                  ['Profit Margin',   s.profit_margins ? `${(s.profit_margins * 100).toFixed(2)}%` : '—'],
                  ['Currency',        s.currency || 'USD'],
                ].map(([label, val]) => (
                  <div key={label} style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid rgba(30,42,66,0.5)' }}>
                    <span style={{ fontSize: 11, color: 'var(--text-muted)',    fontFamily: 'var(--font-mono)' }}>{label}</span>
                    <span style={{ fontSize: 12, color: 'var(--text-primary)', fontFamily: 'var(--font-mono)' }}>{val}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      <div style={styles.bottomDisclaimer}>{DISCLAIMER}</div>
    </div>
  );
};

const styles = {
  page:            { padding: '16px 24px', maxWidth: 1400, margin: '0 auto' },
  nav:             { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  backBtn:         { background: 'transparent', border: '1px solid var(--border)', color: 'var(--text-secondary)', padding: '6px 12px', borderRadius: 'var(--radius)', fontSize: 11, cursor: 'pointer', fontFamily: 'var(--font-mono)', letterSpacing: '0.05em' },
  breadcrumb:      { fontSize: 11, fontFamily: 'var(--font-mono)' },
  hero:            { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)', padding: '24px', marginBottom: 16, gap: 24, flexWrap: 'wrap' },
  heroLeft:        { flex: 1 },
  tickerBig:       { fontFamily: 'var(--font-display)', fontSize: 40, fontWeight: 800, color: 'var(--accent-cyan)', letterSpacing: '-0.02em', lineHeight: 1 },
  companyNameBig:  { fontSize: 16, color: 'var(--text-secondary)', marginTop: 4, fontFamily: 'var(--font-display)', fontWeight: 500 },
  metaTags:        { display: 'flex', gap: 6, marginTop: 12, flexWrap: 'wrap' },
  tag:             { fontSize: 9, color: 'var(--text-secondary)', border: '1px solid var(--border)', borderRadius: 2, padding: '2px 8px', letterSpacing: '0.1em' },
  heroRight:       { textAlign: 'right' },
  priceBig:        { fontFamily: 'var(--font-display)', fontSize: 36, fontWeight: 800, color: 'var(--text-primary)' },
  changeBig:       { fontSize: 18, fontWeight: 600, marginTop: 4, fontFamily: 'var(--font-mono)' },
  heroStats:       { display: 'flex', gap: 16, marginTop: 16, justifyContent: 'flex-end', flexWrap: 'wrap' },
  heroStat:        { display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 2 },
  heroStatLabel:   { fontSize: 9, color: 'var(--text-muted)', letterSpacing: '0.1em' },
  heroStatVal:     { fontSize: 13, color: 'var(--text-primary)', fontFamily: 'var(--font-mono)' },
  tabs:            { display: 'flex', gap: 0, borderBottom: '2px solid var(--border)', marginBottom: 20 },
  tab:             { background: 'transparent', border: 'none', color: 'var(--text-muted)', padding: '10px 20px', fontSize: 11, cursor: 'pointer', fontFamily: 'var(--font-mono)', letterSpacing: '0.1em', borderBottom: '2px solid transparent', marginBottom: -2, transition: 'all 0.15s' },
  tabActive:       { color: 'var(--accent-green)', borderBottomColor: 'var(--accent-green)' },
  content:         { minHeight: 400 },
  periodSelector:  { display: 'flex', alignItems: 'center', marginBottom: 12 },
  periodBtn:       { background: 'transparent', border: '1px solid var(--border)', color: 'var(--text-muted)', padding: '4px 10px', borderRadius: 'var(--radius)', fontSize: 11, cursor: 'pointer', fontFamily: 'var(--font-mono)', marginRight: 4 },
  periodBtnActive: { background: 'var(--bg-elevated)', borderColor: 'var(--accent-cyan)', color: 'var(--accent-cyan)' },
  chartCard:       { background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)', padding: 20 },
  chartTitle:      { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16, fontSize: 11, letterSpacing: '0.1em', fontFamily: 'var(--font-mono)', color: 'var(--text-muted)' },
  disclaimerBox:   { background: 'rgba(245,166,35,0.07)', border: '1px solid rgba(245,166,35,0.3)', borderRadius: 'var(--radius)', padding: '12px 16px', fontSize: 11, color: 'var(--accent-amber)', marginBottom: 20, lineHeight: 1.6, fontFamily: 'var(--font-mono)' },
  noData:          { padding: 40, textAlign: 'center', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', fontSize: 12 },
  bottomDisclaimer:{ marginTop: 32, padding: '12px 16px', background: 'rgba(245,166,35,0.05)', border: '1px solid rgba(245,166,35,0.2)', borderRadius: 'var(--radius)', fontSize: 10, color: 'var(--accent-amber)', fontFamily: 'var(--font-mono)', lineHeight: 1.6 },
};

export default StockDetail;
